version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[npm] [zeroscaler-cdk] "
    versioning-strategy: "increase-if-necessary"
    labels:
      - "dependencies"
      - "npm"
    reviewers:
      - "lephyrius"
    assignees:
      - "lephyrius"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    allow:
      - dependency-type: "direct"
      - dependency-type: "production"

  - package-ecosystem: "cargo"
    directory: "boot-fargate"
    schedule:
      interval: "daily"
    commit-message: 
      prefix: "[cargo] [boot-fargate] "
    versioning-strategy: "increase-if-necessary"
    labels:
      - "dependencies"
      - "rust"
    reviewers:
      - "lephyrius"
    assignees:
      - "lephyrius"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    allow:
      - dependency-type: "direct"
      - dependency-type: "production"

  - package-ecosystem: "cargo"
    directory: "boot-fargate-lambda"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[cargo] [boot-fargate-lambda] "
    versioning-strategy: "increase-if-necessary"
    labels:
      - "dependencies"
      - "rust"
    reviewers:
      - "lephyrius"
    assignees:
      - "lephyrius"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    allow:
      - dependency-type: "direct"
      - dependency-type: "production"