version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[npm] [zeroscaler-cdk] "
  - package-ecosystem: "cargo"
    directory: "boot-fargate"
    schedule:
      interval: "daily"
    commit-message: 
      prefix: "[cargo] [boot-fargate] "
  - package-ecosystem: "cargo"
    directory: "boot-fargate-lambda"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[cargo] [boot-fargate-lambda] "
