[package]
name = "boot-fargate-lambda"
version = "0.1.0"
edition = "2024"

[dependencies]
lambda_http = "0.17"
tokio = { version = "1", features = ["macros"] }
zeroscaler-boot-fargate = { version = "*" }


[profile.release]
lto = true
strip = true
opt-level = "z"