name: Build Boot Fargate Lambda for ARM64

on:
  push:
    branches: [main,build]
  pull_request:

jobs:
  test-crate:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout code for ARM64 build
        uses: actions/checkout@v4

      - name: Install Rust (latest stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu
      - name: Runs the tests.
        working-directory: boot-fargate
        run: cargo test --all-features
  build-crate:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    needs: test-crate
    steps:
      - name: Checkout code for ARM64 build
        uses: actions/checkout@v4

      - name: Install Rust (latest stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu

      - name: Install cargo-lambda
        run: cargo install cargo-lambda --locked

      - name: Build Lambda for ARM64
        working-directory: boot-fargate
        run: |
          cargo lambda build --release --arm64

      - name: Upload Boot Fargate Lambda artifact
        uses: actions/upload-artifact@v4
        with:
          name: boot_fargate_lambda
          path: target/lambda/boot-fargate-lambda/bootstrap