name: Build Boot Fargate Lambda for ARM64

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-lambda:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust (latest stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu

      - name: Install cargo-lambda
        run: cargo install cargo-lambda --locked

      - name: Build Lambda for ARM64
        working-directory: boot_fargate_lambda
        run: |
          cargo lambda build --release --arm64

      - name: Upload Lambda artifact
        uses: actions/upload-artifact@v4
        with:
          name: boot_fargate_lambda
          path: target/lambda/boot_fargate_lambda/bootstrap