name: Build Boot Fargate crate and distribute to crate.io

on:
  push:
    branches: [main,build]
  pull_request:

jobs:
  test-crate:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout code for ARM64 build
        uses: actions/checkout@v4

      - name: Install Rust (latest stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu
      - name: Runs the tests.
        working-directory: boot-fargate
        run: cargo test --all-features
  build-crate:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    needs: test-crate
    steps:
      - uses: actions/checkout@v4
      - name: Cache publish-action bin
        id: cache-publish-action
        uses: actions/cache@v4
        env:
          cache-name: cache-publish-action
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-build-${{ env.cache-name }}-v0.2.0

      # install publish-action by cargo in github action
      - name: Install publish-action
        if: steps.cache-publish-action.outputs.cache-hit != 'true'
        run:
          cargo install publish-action --locked

      - name: Run publish-action
        id: publish-action
        working-directory: boot-fargate
        run:
          publish-action
        env:
          # This can help you tagging the github repository
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # This can help you publish to crates.io
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}